var errorsObj = {
    SERVER_CON: 'SERVER_CON_ERROR',
    ACCESS_DENIED: 'ACCESS_DENIED_ERROR',
    DB_CON: 'DB_CON_ERROR',
    DB_QUERY: 'DB_QUERY_ERROR',
    AUTH: 'AUTH_ERROR',
    WRONG_ID: 'WRONG_ID_ERROR',
    USERNAME: 'USERNAME_ERROR',
    TOKEN_TIME: 'TOKEN_TIME_ERROR',
    VALIDATION: 'VALIDATION_ERROR',
    NO_USERS: 'NO_USERS_ERROR'
};

module.exports = errorsObj;
